[build]
builder = "NIXPACKS"
buildCommand = "chmod +x ./mvnw && ./mvnw -B -DskipTests clean package"

[deploy]
startCommand = "java -Dspring.profiles.active=prod -jar $(ls target/*.jar | head -1)"
restartPolicyType = "ON_FAILURE"
