spring.application.name=internx-project

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/internx}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Soni@123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# JWT
jwt.secret=${JWT_SECRET:internx_super_secret_jwt_key_min_32_chars_2024}
jwt.expiration=${JWT_EXPIRATION:604800000}

# Server
server.port=${PORT:8081}

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME:internx1507@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:uttx osit jwsr ditk}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000

# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dferrfhzk}
cloudinary.api-key=${CLOUDINARY_API_KEY:729848113272365}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:IuNHU2edQ1l3Bb94hgW1UJaPdZc}

# File uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

