spring.application.name=internx-project
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/internx
spring.datasource.username=root
spring.datasource.password=Soni@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=internx2026@secretkey#chanderparkash!
jwt.expiration=846000
server.port=8081
